# Mark Shust's Docker Configuration for Magento (https://github.com/markshust/docker-magento)
# Version 22.0.0

version: "3"

volumes:
  appdata:
#  dbdata:
  sockdata:
  composer:

services:
  app:
    image: markoshust/magento-nginx:1.13-7
    ports:
      - "80:8000"
      - "443:8443"
    links:
  #    - db
      - phpfpm
    volumes: 
      - composer:/var/www/.composer:delegated
      - appdata:/var/www/html
      - sockdata:/sock

  phpfpm:
    image: carpio701021/magento2.3
  #  links:
  #    - db
    volumes: 
      - composer:/var/www/.composer:delegated
      - appdata:/var/www/html
      - sockdata:/sock
    environment:
      - BASE_URL 127.0.0.1
      - DB_HOST "35.236.98.126"
      - DB_NAME "sartorial0301"
      - DB_USER "root"
      - DB_PASSWORD "OvSv7HN5ksW8"
      - ADMIN_FIRSTNAME "John"
      - ADMIN_LASTNAME "Smith"
      - ADMIN_EMAIL "john.smith@gmail.com"
      - ADMIN_USER "john.smith"
      - ADMIN_PASSWORD "McAAPh29aT3N"
      - RABBITMQ_HOSTNAME "35.235.72.193"
      - RABBITMQ_PORT "5672"
      - RABBITMQ_USER "guest"
      - RABBITMQ_PASSWORD "guest"
      - RABBITMQ_VIRTUALHOSTS "/"

  #db:
  #  image: percona:5.7
  #  ports:
  #    - "3306:3306"
  #  env_file: env/db.env
  #  volumes:
  #    - dbdata:/var/lib/mysql

  redis:
    image: redis:5.0

  #elasticsearch:
  #  image: elasticsearch:5.6
  #  ports:
  #    - "9200:9200"
  #    - "9300:9300"

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  image: markoshust/magento-php:7.2-fpm-0
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes
