# Mark Shust's Docker Configuration for Magento (https://github.com/markshust/docker-magento)
# Version 22.0.0

version: "3"


services:
  app:
    image: markoshust/magento-nginx:1.13-7
    ports:
      - "80:8000"
      - "443:8443"
    links:
  #    - db
      - phpfpm
    volumes: 
      - composer:/var/www/.composer:delegated
      - appdata:/var/www/html
      - sockdata:/sock
    depends_on:
      - phpfpm

  phpfpm:
    image: magento2.3
  #  links:
  #    - db
    volumes: 
      - composer:/var/www/.composer:delegated
      - appdata:/var/www/html
      - sockdata:/sock
    environment:
      - BASE_URL 127.0.0.1
      - DB_HOST "35.236.98.126"
      - DB_NAME "sartorial0301"
      - DB_USER "root"
      - DB_PASSWORD "OvSv7HN5ksW8"
      - ADMIN_FIRSTNAME "John"
      - ADMIN_LASTNAME "Smith"
      - ADMIN_EMAIL "john.smith@gmail.com"
      - ADMIN_USER "john.smith"
      - ADMIN_PASSWORD "McAAPh29aT3N"
      - RABBITMQ_HOSTNAME "35.235.72.193"
      - RABBITMQ_PORT "5672"
      - RABBITMQ_USER "guest"
      - RABBITMQ_PASSWORD "guest"
      - RABBITMQ_VIRTUALHOSTS "/"
    depends_on:
      - db
      - elasticsearch
      - rabbit
  
  db:
    image: percona:5.7
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200:9200"
      - "9300:9300"

  rabbit:
    image: rabbitmq:3.7-alpine
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=magento 
      - RABBITMQ_DEFAULT_PASS=magento


volumes:
  appdata:
  dbdata:
  sockdata:
  composer: