# Mark Shust's Docker Configuration for Magento (https://github.com/markshust/docker-magento)
# Version 22.0.0

version: "3"

services:
  
  db:
    image: percona:5.7
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200:9200"
      - "9300:9300"

  rabbit:
    image: rabbitmq:3.7-alpine
    ports:
      - "5672:5672"
    environment:
      - ABBITMQ_DEFAULT_USER=magento 
      - RABBITMQ_DEFAULT_PASS=magento


volumes:
  dbdata:
