apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: phpfpm
  name: phpfpm
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: phpfpm
    spec:
      containers:
      - image: carpio701021/magento2.3-phpfpm
        name: phpfpm
        ports:
        - containerPort: 9000
        - containerPort: 9001
        env:
        - name: BASE_URL
          value: "35.235.120.10"
        - name: DB_HOST
          value: "192.168.16.3"
        - name: DB_NAME
          value: "sartorial0301"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "OvSv7HN5ksW8"
        - name: ADMIN_FIRSTNAME
          value: "John"
        - name: ADMIN_LASTNAME
          value: "Smith"
        - name: ADMIN_EMAIL
          value: "john.smith@gmail.com"
        - name: ADMIN_USER
          value: "john.smith"
        - name: ADMIN_PASSWORD
          value: "McAAPh29aT3N"
        - name: SESSION_REDIS_HOST
          value: "redis-service"
        - name: CACHE_REDIS_HOST
          value: "redis-service"
        - name: CACHE_REDIS_PORT
          value: "6379"
        - name: RABBITMQ_HOSTNAME
          value: "rabbit-service"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "magento0301"
        - name: RABBITMQ_PASSWORD
          value: "lNQT6ySrYRMP"
        - name: RABBITMQ_VIRTUALHOST
          value: "/"
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: appdata
        securityContext:
          allowPrivilegeEscalation: true
      restartPolicy: Always
      volumes:
      - name: appdata
        persistentVolumeClaim:
          claimName: appdata
      securityContext:
          runAsUser: 1000
          fsGroup: 1000
status: {}
